truncate "public"."ocupaciones" RESTART IDENTITY;
insert into ocupaciones(descripcion) values ('NO TIENE EMPLEO PERO SE DEDICA A REPARAR O DAR MANTENIMIENTO A LA VIVIENDA, MUEBLES, APARATOS ELECTRODOMÉSTICOS O VEHÍCULOS');
insert into ocupaciones(descripcion) values ('REALIZA LOS QUEHACERES DE SU HOGAR');
insert into ocupaciones(descripcion) values ('JUBILADO O PENSIONADO');
insert into ocupaciones(descripcion) values ('INCAPACITADO PARA TRABAJAR');
insert into ocupaciones(descripcion) values ('PRESTA SERVICIOS GRATUITOS Y VOLUNTARIOS A SU COMUNIDAD');
insert into ocupaciones(descripcion) values ('DESOCUPADO');
insert into ocupaciones(descripcion) values ('TRABAJADOR POR CUENTA PROPIA');
insert into ocupaciones(descripcion) values ('PATRÓN O EMPLEADOR');
insert into ocupaciones(descripcion) values ('TRABAJADOR REMUNERADO PÚBLICO');
insert into ocupaciones(descripcion) values ('TRABAJADOR REMUNERADO DEL SECTOR PRIVADO');
insert into ocupaciones(descripcion) values ('TRABAJADOR SIN REMUNERACIÓN O SIN PAGO');
