truncate "public"."entidades" RESTART IDENTITY;
insert into entidades (descripcion) values ('Aguascalientes');
insert into entidades (descripcion) values ('Baja California');
insert into entidades (descripcion) values ('Baja California Sur');
insert into entidades (descripcion) values ('Campeche');
insert into entidades (descripcion) values ('Coahuila ');
insert into entidades (descripcion) values ('Colima');
insert into entidades (descripcion) values ('Chiapas');
insert into entidades (descripcion) values ('Chihuahua');
insert into entidades (descripcion) values ('Ciudad de México');
insert into entidades (descripcion) values ('Durango');
insert into entidades (descripcion) values ('Guanajuato');
insert into entidades (descripcion) values ('Guerrero');
insert into entidades (descripcion) values ('Hidalgo');
insert into entidades (descripcion) values ('Jalisco');
insert into entidades (descripcion) values ('México');
insert into entidades (descripcion) values ('Michoacán ');
insert into entidades (descripcion) values ('Morelos');
insert into entidades (descripcion) values ('Nayarit');
insert into entidades (descripcion) values ('Nuevo León');
insert into entidades (descripcion) values ('Oaxaca');
insert into entidades (descripcion) values ('Puebla');
insert into entidades (descripcion) values ('Quintana Roo');
insert into entidades (descripcion) values ('Queretaro');
insert into entidades (descripcion) values ('San Luis Potosí');
insert into entidades (descripcion) values ('Sinaloa');
insert into entidades (descripcion) values ('Sonora');
insert into entidades (descripcion) values ('Tabasco');
insert into entidades (descripcion) values ('Tamaulipas');
insert into entidades (descripcion) values ('Tlaxcala');
insert into entidades (descripcion) values ('Veracruz ');
insert into entidades (descripcion) values ('Yucatán');
insert into entidades (descripcion) values ('Zacatecas');

