truncate "public"."etnicas" RESTART IDENTITY;
insert into etnicas(descripcion) values ('AMUZGOS');
insert into etnicas(descripcion) values ('CAKCHIQUEL');
insert into etnicas(descripcion) values ('CHOLES');
insert into etnicas(descripcion) values ('CHATINO');
insert into etnicas(descripcion) values ('CHICHIMECA JONAZ');
insert into etnicas(descripcion) values ('CHINANTECO');
insert into etnicas(descripcion) values ('CHOCHO');
insert into etnicas(descripcion) values ('CHONTAL DE OAXACA');
insert into etnicas(descripcion) values ('CHONTAL DE TABASCO');
insert into etnicas(descripcion) values ('CHUJ');
insert into etnicas(descripcion) values ('COCHIMÍ');
insert into etnicas(descripcion) values ('CORAS');
insert into etnicas(descripcion) values ('CUCAPÁS');
insert into etnicas(descripcion) values ('CUICATECO');
insert into etnicas(descripcion) values ('GUARIJÍO');
insert into etnicas(descripcion) values ('HUASTECO');
insert into etnicas(descripcion) values ('HUAVE');
insert into etnicas(descripcion) values ('HUICHOLES');
insert into etnicas(descripcion) values ('IXCATECO');
insert into etnicas(descripcion) values ('IXILES');
insert into etnicas(descripcion) values ('JAKALTEKOS');
insert into etnicas(descripcion) values ('KICHES');
insert into etnicas(descripcion) values ('KANJOBALES');
insert into etnicas(descripcion) values ('KAQCHIKELES');
insert into etnicas(descripcion) values ('KIKAPU');
insert into etnicas(descripcion) values ('KILIWA');
insert into etnicas(descripcion) values ('KUMIAIS');
insert into etnicas(descripcion) values ('LACANDONES');
insert into etnicas(descripcion) values ('MAMES');
insert into etnicas(descripcion) values ('MATLATZINCA');
insert into etnicas(descripcion) values ('MAYA');
insert into etnicas(descripcion) values ('MAYOS');
insert into etnicas(descripcion) values ('MAZAHUA');
insert into etnicas(descripcion) values ('MAZATECOS');
insert into etnicas(descripcion) values ('MEXICANEROS DE DURANGO (NAHUAS)');
insert into etnicas(descripcion) values ('MIXES');
insert into etnicas(descripcion) values ('MIXTECO');
insert into etnicas(descripcion) values ('MIXTECO MIXTECA ALTA');
insert into etnicas(descripcion) values ('MIXTECO MIXTECA BAJA');
insert into etnicas(descripcion) values ('MIXTECO ZONA MAZATECA');
insert into etnicas(descripcion) values ('MIXTECOS');
insert into etnicas(descripcion) values ('MOCHÓS');
insert into etnicas(descripcion) values ('NÁHUATL');
insert into etnicas(descripcion) values ('OCUITLECO');
insert into etnicas(descripcion) values ('OTOMÍ');
insert into etnicas(descripcion) values ('P’URHÉPECHAS');
insert into etnicas(descripcion) values ('PAIPAI');
insert into etnicas(descripcion) values ('PAMES');
insert into etnicas(descripcion) values ('PÁPAGO');
insert into etnicas(descripcion) values ('PIMA');
insert into etnicas(descripcion) values ('POPOLOCA');
insert into etnicas(descripcion) values ('POPOLUCAS');
insert into etnicas(descripcion) values ('SERIS');
insert into etnicas(descripcion) values ('TACUATES');
insert into etnicas(descripcion) values ('TARAHUMARA');
insert into etnicas(descripcion) values ('TEPEHUAN DEL NORTE');
insert into etnicas(descripcion) values ('TEPEHUANOS DEL SUR');
insert into etnicas(descripcion) values ('TLAPANECOS');
insert into etnicas(descripcion) values ('TOJOLABAL');
insert into etnicas(descripcion) values ('TOTONACA');
insert into etnicas(descripcion) values ('TRIQUIS');
insert into etnicas(descripcion) values ('TSOTSILES');
insert into etnicas(descripcion) values ('TZELTAL');
insert into etnicas(descripcion) values ('YAQUI');
insert into etnicas(descripcion) values ('ZAPOTECO DE LA SIERRA NORTE');
insert into etnicas(descripcion) values ('ZAPOTECO DEL ISTMO');
insert into etnicas(descripcion) values ('ZAPOTECOS DE VALLES CENTRALES');
insert into etnicas(descripcion) values ('ZOQUE');

