truncate "public"."alcaldias";
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (1, 'ÁLVARO OBREGÓN', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (2, 'AZCAPOTZALCO', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (3, 'BENITO JUÁREZ', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (4, 'COYOACÁN', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (5, 'CUAUHTÉMOC', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (6, 'CUAJIMALPA DE MORELOS', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (7, 'GUSTAVO A. MADERO', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (8, 'IZTACALCO', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (9, 'IZTAPALAPA', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (10, 'MAGDALENA CONTRERAS', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (11, 'MIGUEL HIDALGO', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (12, 'MILPA ALTA', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (13, 'TLÁHUAC', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (14, 'TLALPAN', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (15, 'VENUSTIANO CARRANZA', 1);
INSERT INTO "public"."alcaldias" (id_cat_alcaldia,descripcion,estatus) VALUES (16, 'XOCHIMILCO', 1);
